### ISSUE TITLE
Client doesn't send correct status message

### ISSUE THREAD

**Issue by jayconnor-lab** [russrimm/CollectAllLogs#2]
Status message 1234 Description:
The Status Message Viewer could not locate the file containing the description strings for messages from CCMLogGatherer. CCMLogGatherer is not registered via the Configuration Manager site control file as a source of status messages, nor is it registered via the HKEY_LOCAL_MACHINE\System\CurrentControlSet\Services\EventLog registry keys as a source of Windows NT Events. This problem could occur if you configured Configuration Manager to collect NT Events from CCMLogGatherer but CCMLogGatherer is not installed on the machine you're running the Status Message Viewer on. Please install CCMLogGatherer on this machine or run the Status Message Viewer on a machine CCMLogGatherer is already installed on. This problem could also occur if CCMLogGatherer is a defective add-on product to Configuration Manager that reports Configuration Manager status messages, or if site MU2 is a newer version of Configuration Manager than site . Please contact Microsoft for more information.The Status Message Viewer could not locate the file containing the description strings for messages from CCMLogGatherer. CCMLogGatherer is not registered via the Configuration Manager site control file as a source of status messages, nor is it registered via the HKEY_LOCAL_MACHINE\System\CurrentControlSet\Services\EventLog registry keys as a source of Windows NT Events. This problem could occur if you configured Configuration Manager to collect NT Events from CCMLogGatherer but CCMLogGatherer is not installed on the machine you're running the Status Message Viewer on. Please install CCMLogGatherer on this machine or run the Status Message Viewer on a machine CCMLogGatherer is already installed on. This problem could also occur if CCMLogGatherer is a defective add-on product to Configuration Manager that reports Configuration Manager status messages, or if site MU2 is a newer version of Configuration Manager than site . Please contact Microsoft for more information.

**Comment by jayconnor-lab** [comment]
Ignore me.. Status message is coming correctly, just not viewable in the viewer. It looks like the script on the Site Server is having some issues but gets the MP and file name correctly. Will keep working at it

**Comment by jayconnor-lab** [comment]
Issue in MoveLogToPrimary.ps1

Replace $ParentLogFolder with $LogFolder

**Comment by russrimm** [comment]
Updated to $LogFolder, thanks @jayconnor-lab
